[project]
name = "my_custom_pkg"
dependencies = [
    "scipy >= 1.3.3",
    "pandas >= 1.3.0",
    "featuretools >= 1.5.0, <2.0.0",
    "woodwork >= 0.8.1",
]

[project.optional-dependencies]
dev = [
    "autopep8 >= 1.6.0",
    "pandas < 1.4.0",
]

test = [
    "pip >= 22.0.2",
    "wheel >= 0.37.1",
    "pytest >= 5.2.0",
]