name: Integration Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  integration_test:
    name: integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run Minimum Dependency Generator GitHub Action
        id: min_dep_gen
        uses: ./
        with:
          requirements_paths: 'test-requirements.txt requirements.txt'
      - name: Get the output time
        run: echo "The time was ${{ steps.min_dep_gen.outputs }}"
      - name: Get the output time
        run: echo "The time was ${{ steps.min_dep_gen.outputs.min_reqs }}"