name: Lint Check
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  lint_check:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run lint check for minimum dependency generator
        run: |
          python -m pip install -r test-requirements.txt
          make lint
