name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run unit tests for minimum dependency generator
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test-requirements.txt
          coverage erase
          make testcoverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true